ci:
  # Replace use some hooks of pre-commit.ci with our own github actions.
  # See https://github.com/pre-commit-ci/issues/issues/55.
  skip: ["pyright"]
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: trailing-whitespace
        args: [--markdown-linebreak-ext=md]
      - id: end-of-file-fixer
        exclude: (?x)(^.*/.*\.svg$)
      - id: check-json
      - id: check-toml
      - id: check-added-large-files

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.18.0
    hooks:
      - id: pyupgrade
        args: [--py37-plus]

  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.19.0
    hooks:
      - id: blacken-docs
        additional_dependencies: [black]

  - repo: https://github.com/MarcoGorelli/absolufy-imports
    rev: v0.3.1
    hooks:
      - id: absolufy-imports

  - repo: https://github.com/PyCQA/isort
    rev: 5.13.2
    hooks:
      - id: isort

  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        entry: pflake8
        additional_dependencies: &flake8_dependencies
          - pyproject-flake8
          - pep8-naming
          - flake8-print
          - flake8-return
          - flake8-simplify
          - flake8-bugbear
          - flake8-docstrings
          - flake8-comprehensions
          - flake8-eradicate
          - flake8-rst-docstrings
          - flake8-pytest-style

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        additional_dependencies: *flake8_dependencies

  - repo: https://github.com/pre-commit/pygrep-hooks
    rev: v1.10.0
    hooks:
      - id: rst-backticks
      - id: rst-directive-colons
      - id: rst-inline-touching-normal
      - id: python-no-eval
      - id: python-no-log-warn
      - id: python-use-type-annotations

  - repo: local
    hooks:
      - id: pyright
        name: pyright
        entry: pyright
        language: python
        pass_filenames: false
        types: [python]
        additional_dependencies:
          - pyright
          - PyQt6
          - rich
          - pytest
          - qtpy
          - pyserial
          - pyqtdarktheme
          - darkdetect
          - qtawesome
          - pyinstaller
          - git+https://github.com/5yutan5/pyAutoLab
          - PyQtGraph
          - numpy
          - psutil
